#!/usr/bin/env python3
"""Test harness for TaskFlow MCP Server.

Validates that all MCP tools, resources, and vault reader/writer functions
work correctly in isolation without requiring external network or live agent.
"""
from __future__ import annotations

import os
import shutil
import sys
import tempfile
from pathlib import Path

# Add sidecar directory to sys.path
sidecar_dir = Path(__file__).parent.resolve()
if str(sidecar_dir) not in sys.path:
    sys.path.insert(0, str(sidecar_dir))

import mcp_server


def test_mcp_tools():
    print("=== Testing TaskFlow MCP Server ===")

    # 1. Setup temporary test vault
    temp_dir = Path(tempfile.mkdtemp(prefix="taskflow_mcp_test_"))
    vault_dir = temp_dir / "TestVault"
    tf_root = vault_dir / "TaskFlow"
    projects_dir = tf_root / "Projects"
    memory_dir = tf_root / "Memory" / "Daily"

    projects_dir.mkdir(parents=True, exist_ok=True)
    memory_dir.mkdir(parents=True, exist_ok=True)

    # Populate test project
    (projects_dir / "sample-project.md").write_text("""# Sample Project

Workstream description for sample project.

## Activity Timeline
- 10:00 AM: Worked on initial setup
- 11:30 AM: Fixed compiler bugs
""", encoding="utf-8")

    # Populate test daily note
    import datetime
    today_str = datetime.date.today().isoformat()
    (memory_dir / f"{today_str}.md").write_text(f"""# Daily Notes for {today_str}

## Highlights
- Accomplished major tasks
- Tested MCP integration
""", encoding="utf-8")

    # Point environment to test vault
    os.environ["TASKFLOW_VAULT"] = str(vault_dir)

    try:
        # Test 1: list_vault_tree
        print("\n[Test 1] Testing list_vault_tree()...")
        tree = mcp_server.list_vault_tree()
        assert tree["file_count"] >= 2, f"Expected >= 2 files, got {tree['file_count']}"
        print(f"  Passed! Found {tree['file_count']} files in vault.")

        # Test 2: list_projects
        print("\n[Test 2] Testing list_projects()...")
        projects = mcp_server.list_projects()
        slugs = [p["slug"] for p in projects]
        assert "sample-project" in slugs, f"Expected 'sample-project' in {slugs}"
        print(f"  Passed! Projects: {slugs}")

        # Test 3: read_project
        print("\n[Test 3] Testing read_project('sample-project')...")
        proj = mcp_server.read_project("sample-project")
        assert "Activity Timeline" in proj["content"], "Expected Activity Timeline in content"
        print("  Passed! Project content loaded correctly.")

        # Test 4: read_daily_note
        print("\n[Test 4] Testing read_daily_note('today')...")
        daily = mcp_server.read_daily_note("today")
        assert daily["exists"] is True, "Expected daily note to exist"
        assert "Tested MCP integration" in daily["content"]
        print("  Passed! Daily note read successfully.")

        # Test 5: search_vault (keyword)
        print("\n[Test 5] Testing search_vault (keyword)...")
        results = mcp_server.search_vault("compiler bugs", semantic=False)
        assert len(results) > 0, "Expected search results for 'compiler bugs'"
        assert "sample-project" in results[0]["path"]
        print(f"  Passed! Found {len(results)} matches.")

        # Test 6: search_vault (semantic if torch/sentence_transformers available)
        print("\n[Test 6] Testing search_vault (semantic similarity)...")
        try:
            sem_results = mcp_server.search_vault("fixing errors in code", semantic=True)
            print(f"  Semantic search returned {len(sem_results)} results. Top score: {sem_results[0]['score']}")
            assert len(sem_results) > 0
            print("  Passed! Semantic vector search verified.")
        except Exception as e:
            print(f"  Skipping semantic search due to environment constraint: {e}")

        # Test 7: create_inbox_note
        print("\n[Test 7] Testing create_inbox_note()...")
        inbox_res = mcp_server.create_inbox_note(
            title="Agent Meeting Summary",
            content="Summary generated by Hermes agent.",
            tags=["hermes", "ai-meeting"]
        )
        assert inbox_res["success"] is True
        inbox_file = Path(inbox_res["path"])
        assert inbox_file.exists()
        assert "tags: [hermes, ai-meeting, agent-note]" in inbox_file.read_text(encoding="utf-8")
        print(f"  Passed! Created inbox note at: {inbox_file.name}")

        # Test 8: append_project_note
        print("\n[Test 8] Testing append_project_note()...")
        append_res = mcp_server.append_project_note(
            project_slug="sample-project",
            note="Agent suggests adding unit test for parser."
        )
        assert append_res["success"] is True
        updated_content = (projects_dir / "sample-project.md").read_text(encoding="utf-8")
        assert "## Agent Notes" in updated_content
        assert "Agent suggests adding unit test" in updated_content
        assert "## Activity Timeline" in updated_content  # Activity timeline untouched!
        print("  Passed! Agent note safely appended without touching activity timeline.")

        # Test 9: Resources
        print("\n[Test 9] Testing MCP resources...")
        r_daily = mcp_server.resource_daily_today()
        assert "Daily Notes" in r_daily
        r_projects = mcp_server.resource_projects()
        assert "sample-project" in r_projects
        print("  Passed! Resources verified.")

        print("\nALL MCP TESTS PASSED SUCCESSFULLY! The server is fully operational.")
        return 0
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(test_mcp_tools())
